# Project information
site_name: 'iCub Tech Docs'
site_description: 'upgrade kits: Eyes support'
site_author: 'We, the People of the iCub Tech'
#site_url: 'https://github.com/icub-tech/documentation'

# Repository
#repo_name: icub-tech/documentation
#repo_url: 'https://github.com/icub-tech/documentation'
#edit_uri: 'edit/master/doc/mkdocs/data'

# Configuration
#docs_dir: 'data'
theme:
    name: 'material'
    palette:
    #    primary: blue grey
        primary: teal
        accent: amber
    feature:
        tabs: true
    # favicon:
    #     icon: dashboard
    logo:
        icon: dashboard

# Copyright
copyright: 'Copyright &copy; 2019 Istituto Italiano di Tecnologia - iCub Tech'

# Extensions
markdown_extensions:
    - markdown.extensions.admonition
    # - markdown.extensions.codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.highlight
    - pymdownx.keys
    - pymdownx.magiclink:
        user: robotology
        repo: assistive-rehab
        repo_url_shortener: true
        repo_url_shorthand: true
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - markdown.extensions.toc:
        permalink: true

# Page tree
nav:
    - iCub Tech Docs: 
        - hhh: https://icub-tech-iit.github.io/documentation/mkdocs/thedocs/site/
    - Index: 'index.md' 
    - Instructions: 'Eyes support.md'
    - License: 'license.md'

