site_name: 'iCub Cabling Manual'
site_description: 'tbd'
site_author: 'We, the People of the iCub Tech'

# Configuration
#docs_dir: 'data'
theme:
    name: 'material'
    palette:
    #    primary: blue grey
        primary: orange
        accent: amber
    feature:
        tabs: true
    #favicon:
    #   icon: dashboard
    logo:
        icon: dashboard

# Copyright
copyright: 'Copyright &copy; 2019 Istituto Italiano di Tecnologia - iCub Tech'

# Extensions
markdown_extensions:
    - markdown.extensions.admonition
    # - markdown.extensions.codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.highlight
    - pymdownx.keys
    - pymdownx.magiclink:
        user: robotology
        repo: assistive-rehab
        repo_url_shortener: true
        repo_url_shorthand: true
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - markdown.extensions.toc:
        permalink: true

# Page tree
nav:
    - iCub Tech Docs: 
        - hhh: https://icub-tech-iit.github.io/documentation/mkdocs/thedocs/site/
    - The iCub cabling manual: 'index.md'
    - The body parts:
        - The neck: 'neck.md'
        - The shoulder and elbow: 'shoulder_elbow.md'
        - The lower arm:
              - Definition: 'lower_arm.md'
              - Version 1 :
                   - Hand Cabling V1 - Building Phase: 'hand_cabling_V1.md'
                   - Wrist Cabling: 'wrist_cabling.md'
                   - Lower Arm V1 - Repair Phase : 'lower_arm_V1.md'
              - Version 2 :
                   - Lower Arm V2: 'lower_arm_V2.md'
                   - Wrist Hand Cabling V2: 'wrist_hand_cabling_V2.md'
        - The waist, leg and ankle: 'waist_legs.md'

    - License: 'license.md'