site_name: 'iCub Cabling Manual'
site_description: 'tbd'
site_author: 'We, the People of the iCub Tech'

# Configuration
#docs_dir: 'data'
theme:
    name: 'material'
    palette:
    #    primary: blue grey
        primary: orange
        accent: amber
    feature:
        tabs: true
    #favicon:
    #   icon: dashboard
    logo:
        icon: dashboard

# Copyright
copyright: 'Copyright &copy; 2019 Istituto Italiano di Tecnologia - iCub Tech'

# Extensions
markdown_extensions:
    - markdown.extensions.admonition
    # - markdown.extensions.codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.highlight
    - pymdownx.keys
    - pymdownx.magiclink:
        user: robotology
        repo: assistive-rehab
        repo_url_shortener: true
        repo_url_shorthand: true
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - markdown.extensions.toc:
        permalink: true

# Page tree
nav:
    - iCub Tech Docs: 
        - hhh: https://icub-tech-iit.github.io/documentation/mkdocs/thedocs/site/
    - The iCub cabling manual: 'index.md'
    - Body Parts:
        - Neck: 'neck.md'
        - Shoulder and Elbow: 'shoulder_elbow.md'
        - Lower Arm:
            - Definition: 'lower_arm.md'
            - Version 1 :
                - Building Phase:
                    - HOWTO CABLE & NEEDED PARTS V1: 'hand_cabling_V1.md'
                - Repair Phase:
                    - Disconnection V1: 'remove.md'
                    - Lower Arm V1 : 'lower_arm_V1.md'
                    - Wrist & Hand Cabling V1: 'wrist_cabling.md'
            - Version 2 :
                - Building Phase:
                    - HOWTO CABLE & NEEDED PARTS V2: 'cabling_V2.md'
                - Repair Phase:
                    - Disconnection V2: 'remove/#2-lower-arm-v2'
                    - Lower Arm V2: 'lower_arm_V2.md'
                    - Wrist & Hand Cabling V2: 'wrist_hand_cabling_V2.md'
        - Waist, Leg and Ankle: 'waist_legs.md'

    - License & thx: 'license.md'