name: Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON" 

jobs:
  docs:
    name: "Check"
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        run: |
          pip install git+https://github.com/linkchecker/linkchecker.git
          
      - name: Fetch repository name
        id: repo-name
        run: |
          echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_OUTPUT
        
      - name: Run checker
        run: |
          linkchecker https://${{ github.repository_owner }}.github.io/${{ steps.repo-name.outputs.REPOSITORY_NAME }}/ --check-extern --no-warnings
