name: Test PR

on:
  pull_request:

jobs:
  docs:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-wheel python3-setuptools
          pip3 install --user mkdocs mkdocs-material pymdown-extensions
          echo "::set-env name=PATH::${HOME}/.local/bin:$PATH"
        
      - name: Build Mkdocs
        run: |
          mkdocs build
