name: Update SW Distros

on:
  workflow_dispatch:
    inputs:
      superbuild_tag:
        description: 'The robotology-superbuild tag to refer to'
        required: true
        default: 'master'
      initial_distro:
        description: 'The initial SW Distro to process (e.g. 0000.00 will process all distros)'
        required: true
        default: '2021.11.0'

concurrency:
  group: update_sw_distros
  cancel-in-progress: true

jobs:
  Update:
    name: "Update"
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo gem install yaml
      - name: Set Env Variables
        run: |
          echo "SUPERBUILD_TAG=${{ inputs.superbuild_tag }}" >> ${GITHUB_ENV}
          echo "INITIAL_DISTRO=${{ inputs.initial_distro }}" >> ${GITHUB_ENV}
          echo "SUPERBUILD_RELEASES_PATH=${{ github.workspace }}/../robotology-superbuild/releases" >> ${GITHUB_ENV}
          echo "SW_VERSIONING_TABLE_PATH=${{ github.workspace }}/docs/sw_versioning_table" >> ${GITHUB_ENV}
      - uses: actions/checkout@main
      - name: Download Robotology Superbuild
        run: |
          cd ../
          git clone https://github.com/robotology/robotology-superbuild.git --depth 1 --branch ${SUPERBUILD_TAG}
      - name: Run Updater
        run: |
          rm -Rf ${SW_VERSIONING_TABLE_PATH}
          cd scripts/sw-distros
          ./update-sw-distros.rb          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@main
        with:
          commit-message: Automatic update of docs for Distro ${{ inputs.superbuild_tag }}
          branch: automatic-update-docs-distro-${{ inputs.superbuild_tag }}
          delete-branch: true
          title: 'Automatic update of Docs for Distro `${{ inputs.superbuild_tag }}`'
          reviewers: pattacini
          assignees: ${{ github.actor }}
          body: |
            This PR has been triggered with the following options:
            - Superbuild tag: `${{ inputs.superbuild_tag }}`
            - Initial distro to document: `${{ inputs.initial_distro }}`.
      - name: Check outputs
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"          
          
